### ISSUE TITLE
move main repo

### ISSUE THREAD

**Issue by cbm755** [gnu-octave/octave-doctest#277]
We are happy as https://github.com/catch22/octave-doctest but community ownership is good too...   We have discussed moving before, most recently https://github.com/catch22/octave-doctest/issues/274#issuecomment-1370219079

If we did move, a good choice would probably be:

https://github.com/gnu-octave/

**Comment by catch22** [comment]
Could one of the Octave folks (@mmuetzel?) advise on whether this is an option and how we would go about this?

**Comment by mmuetzel** [comment]
There are already a few Octave packages that host their main sources in a repository of the @gnu-octave organization. So, this definitely is an option for this Octave package, too.

As to how that could be done, there seems to be some documentation here:
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by siko1056** [comment]
@catch22, @cbm755, and @mmuetzel .  I would greatly appreciate moving this repository to https://github.com/gnu-octave/ .  The idea of this organization was to give Octave related software on GitHub a place to be found.  Projects are still very wide spread and often difficult to find.  You all got "owner" permissions (same as me) for this organization. Thus no fear of being locked-in.  Do whatever you think is the best for your projects and Octave.

For Octave Packages one can host the code at any convenient location.  There are no restrictions about the current location on GitHub.

**Comment by cbm755** [comment]
Thank you both for your comments.

The usual downside of moving a repo is confusion, especially for downstream folks with local repo clones.  However, from the docs that @mmuetzel linked to it seems this is mitigated:

> All links to the previous repository location are automatically redirected to the new location.

Based on all the above I'm in favour of moving to the gnu-octave group.  But will leave decision to @catch22.

**Comment by cbm755** [comment]
> happy to initiate the transfer whenever is convenient time for you

Anytime works for me.

**Comment by catch22** [comment]
Done!
